name: "SnykJar Test"

on:
  push:
    branches:
    - master
    

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}
    
    # Install Maven
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@3.8.5
      with:
          java-version: 8
          maven-version: 3.8.5
    
    # Run Snyk Code
    - name: Running Snyk Code on JARs
      run: |
         snyk test --scan-all-unmanaged  
      # continue-on-error: true
