on:
  push:
    branches:
    - master


jobs:
  Pipeline-Job:
    # Configure Environment
 
  snyk:
    name: 'Snyk Test'  
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
    steps:
# Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
      run: |
         sudo npm install -g snyk
         snyk auth ${{secrets.SNYK_TOKEN}}
    # Docker Build
    - name: Build Container     
      run: |
         docker build .  -t curtisjones00/snyk-juice-shop:latest
    # Run Snyk Container     
    - name: Run Snyk Container
      run: |
         snyk container test --file=Dockerfile curtisjones00/snyk-juice-shop:latest --severity-threshold=high --sarif > snykv1.sarif
      continue-on-error: true  
      
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snykv1.sarif
